### ISSUE TITLE
Community chat

### ISSUE THREAD

**Issue by le2Ks** [qogecoin/qogecoin-legacy#1]
Hi, is there any discord or telegram group for the project? ty

**Comment by qogecoin-dev** [comment]
Not yet, we will build a discord server.

**Comment by bitcoin-africa** [comment]
> Not yet, we will build a discord server.

Hi, okk thanks

**Comment by le2Ks** [comment]
> 
> Not yet, we will build a discord server.

Hello, ok we will wait :)

**Comment by le2Ks** [comment]
Closing the issue, found the discord link in the readme file, thank you!
